### ISSUE TITLE
Cannot succeed to query DynamoDB as in you sample

### ISSUE THREAD

**Issue by ghost** [BruceBuckland/SignIn-awsmhh#6]
I took your NoSQL code as sample for my own code. But I cannot succeed to load any data!

```
    func getItemWithCompletionHandler(completionHandler: (response: AWSDynamoDBObjectModel?, error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.defaultDynamoDBObjectMapper()
        objectMapper.load(Graffiti.self, hashKey: AWSIdentityManager.defaultIdentityManager().identityId!, rangeKey: 1111500000, completionHandler: {(response: AWSDynamoDBObjectModel?, error: NSError?) -> Void in
            dispatch_async(dispatch_get_main_queue(), {
                completionHandler(response: response, error: error)
            })
        })
    }
```

`response` parameter appears to be `nil` but log displayed a response with valid. It seems mapping to table model object does not work.

I even try another request to query a list of data. In this situation too log indicate data has been successfully retrieved but code crash at object mapping.

Have you ever encountered such cases?

**Comment by BruceBuckland** [comment]
I may not be understanding you but let me mention, while this may be obvious, The mobile hub website sets up the tables...you can't just run the demo you have to configure the tables first

**Comment by ghost** [comment]
I've already my own tables configured and filled with data. That's why I don't understand what is the problem I am facing. Data are successfully retrieved by the app as stating by logs but mapping silently failed.

**Comment by BruceBuckland** [comment]
ok, sorry... no experience with this.  Other than the Mobile Hub demo I have not used DynamoDB, but I plan to soon.  Sorry I don't have more.

**Comment by ghost** [comment]
Can you please contact me via my website to have discussion outside this project?
http://www.domsware.com/en/contact

**Comment by ghost** [comment]
Problem solved!
Model properties contained capital letters. Removing them make the process work.

Hereafter is presented the non working code. In the project field name on DynamoDB must begin with a capital letter. I then created properties following this rule, with an added prefixing underscore.

    class MyModel: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _UserId: String?
    var _ArticleId: String?

    
    class func dynamoDBTableName() -> String {

        return "myTable"
    }
    
    class func hashKeyAttribute() -> String {

        return "_UserId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_ArticleId"
    }
    
    override class func JSONKeyPathsByPropertyKey() -> [NSObject : AnyObject] {
        return [
               "_UserId" : "UserId",
               "_ArticleId" : "ArticleId",

        ]
    }
}


An this is the working code:

    class MyModel: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _articleId: String?

    
    class func dynamoDBTableName() -> String {

        return "myTable"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_articleId"
    }
    
    override class func JSONKeyPathsByPropertyKey() -> [NSObject : AnyObject] {
        return [
               "_userId" : "UserId",
               "_articleId" : "ArticleId",

        ]
    }
}

Strange, isn't it?
